import { access, readFile, writeFile } from "node:fs/promises";
import type { MemoryEntry } from "../core/schema.js";

const START_MARKER = "<!-- whyanchor:start -->";
const END_MARKER = "<!-- whyanchor:end -->";

/** A file whose markers are damaged — refused rather than guessed at. */
export class MarkerError extends Error {}

export type UpsertResult = "created" | "updated" | "unchanged";

// A rendered line that is exactly a marker would be mistaken for the real one on the next run.
const MARKER_LINE = /^<!--\s*whyanchor:[\w:-]+\s*-->$/;

function renderEntry(entry: MemoryEntry): string {
  const { date, refs, tags, status } = entry.frontmatter;
  const title = entry.frontmatter.title.replace(/\s+/g, " ").trim();
  const meta: string[] = [date];
  if (refs.length) meta.push(`refs: ${refs.join(", ")}`);
  if (tags.length) meta.push(`tags: ${tags.join(", ")}`);
  const badge = status !== "active" ? ` _(${status})_` : "";
  const firstLine = (entry.body.split("\n").find((l) => l.trim().length > 0) ?? "").trim();
  const summary = MARKER_LINE.test(firstLine) ? `\`${firstLine}\`` : firstLine;
  return `- **${title}**${badge} (${meta.join(" · ")})\n  ${summary}`;
}

/**
 * Each note is listed once, under its first tag — its meta line still shows every tag — so a note
 * with three tags isn't injected into an agent's context three times.
 */
function groupByPrimaryTag(entries: MemoryEntry[]): Map<string, MemoryEntry[]> {
  const groups = new Map<string, MemoryEntry[]>();
  for (const entry of entries) {
    const tag = entry.frontmatter.tags[0] ?? "general";
    if (!groups.has(tag)) groups.set(tag, []);
    groups.get(tag)!.push(entry);
  }
  return groups;
}

export function renderMemorySection(entries: MemoryEntry[]): string {
  const active = entries.filter((e) => e.frontmatter.status !== "superseded");
  if (active.length === 0) {
    return [START_MARKER, "## Project Memory", "", "_No memory entries yet. Run `whyanchor capture` to add one._", END_MARKER].join(
      "\n"
    );
  }

  const groups = groupByPrimaryTag(active);
  const lines: string[] = [
    START_MARKER,
    "## Project Memory",
    "",
    "Captured decisions and context for this repo. Generated by `whyanchor generate` — do not edit inside this block, it will be overwritten.",
    "",
  ];

  const sortedTags = [...groups.keys()].sort();
  for (const tag of sortedTags) {
    lines.push(`### ${tag}`, "");
    for (const entry of groups.get(tag)!) {
      lines.push(renderEntry(entry));
    }
    lines.push("");
  }

  lines.push(END_MARKER);
  return lines.join("\n").replace(/\n{3,}/g, "\n\n");
}

export interface UpsertOptions {
  startMarker?: string;
  endMarker?: string;
  /** When the section is new, insert it above this marker line instead of appending. */
  insertBefore?: string;
}

/** The line ending most of `text` uses, so edits can be written back without mixing endings. */
export function dominantEol(text: string): "\n" | "\r\n" {
  const crlf = text.match(/\r\n/g)?.length ?? 0;
  const lf = (text.match(/\n/g)?.length ?? 0) - crlf;
  return crlf > lf ? "\r\n" : "\n";
}

function lineIndicesOf(lines: string[], value: string): number[] {
  const out: number[] = [];
  lines.forEach((l, i) => l === value && out.push(i));
  return out;
}

export async function upsertMarkedSection(
  filePath: string,
  section: string,
  options: UpsertOptions = {}
): Promise<UpsertResult> {
  const startMarker = options.startMarker ?? START_MARKER;
  const endMarker = options.endMarker ?? END_MARKER;
  const block = section.replace(/\r\n/g, "\n");

  let existing: string;
  try {
    existing = await readFile(filePath, "utf8");
  } catch {
    await writeFile(filePath, block + "\n", "utf8");
    return "created";
  }

  // Splice in LF, then write back with the file's own line endings — inserting LF text into a
  // CRLF file (the Windows default under core.autocrlf) would leave it with mixed endings.
  const eol = dominantEol(existing);
  const text = existing.replace(/\r\n/g, "\n");
  const lines = text.split("\n");

  // Match markers only on lines that consist solely of the marker — an entry's rendered
  // body can legitimately mention "<!-- whyanchor:end -->" as plain text (e.g. an entry
  // documenting this very marker scheme), and a naive indexOf would match that instead of
  // the real closing marker, corrupting the file.
  const trimmedLines = lines.map((l) => l.trim());
  const starts = lineIndicesOf(trimmedLines, startMarker);
  const ends = lineIndicesOf(trimmedLines, endMarker);

  let next: string;
  if (starts.length === 1 && ends.length === 1 && ends[0] > starts[0]) {
    const before = lines.slice(0, starts[0]).join("\n");
    const after = lines.slice(ends[0] + 1).join("\n");
    next = (before ? before + "\n" : "") + block + (after ? "\n" + after : "\n");
  } else if (starts.length === 0 && ends.length === 0) {
    const anchor = options.insertBefore ? trimmedLines.indexOf(options.insertBefore) : -1;
    if (anchor !== -1) {
      const before = lines.slice(0, anchor).join("\n");
      const after = lines.slice(anchor).join("\n");
      next = (before ? before + "\n" : "") + block + "\n\n" + after;
    } else if (text.trim() === "") {
      next = block + "\n";
    } else {
      const sep = text.endsWith("\n") ? "\n" : "\n\n";
      next = text + sep + block + "\n";
    }
  } else {
    // A lone or duplicated marker (a bad merge, an accidental delete) leaves no way to tell which
    // lines are generated. Guessing "first start to last end" deletes whatever hand-written text
    // sits between an orphaned marker and the real block, so refuse instead.
    throw new MarkerError(
      `${filePath} has ${starts.length} "${startMarker}" and ${ends.length} "${endMarker}" line(s) — ` +
        `expected exactly one of each, start before end. Nothing was changed: restore the missing ` +
        `marker or delete the stray one (or the whole block), then re-run.`
    );
  }

  const output = eol === "\r\n" ? next.replace(/\n/g, "\r\n") : next;
  if (output === existing) return "unchanged";
  await writeFile(filePath, output, "utf8");
  return "updated";
}

export async function upsertMemorySection(filePath: string, section: string): Promise<UpsertResult> {
  return upsertMarkedSection(filePath, section);
}

export async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}
